#yaml pipeline
trigger:
  none

agent:
  vmImage:ubuntu-latest

stages:
  - stage:
    displayName: 'maven_package'
    jobs:
      - job: package
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'Boardgame/pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
             